### ISSUE TITLE
Can df21 extract feature like cnn when used in object detection?

### ISSUE THREAD

**Issue by LMerCy** [LAMDA-NJU/Deep-Forest#1]
Or we need to extract feature with hog/sift etc...

**Comment by xuyxu** [comment]
Hi @LMerCy, thanks for the issue. If what you mean is to generating descriptors using the model, I think the answer so for is NO.

 Is there any work studying how to achieve this with forest? If exists, I would be happy to read it and try out in deep forest ;-).

**Comment by xuyxu** [comment]
Closed due to inactivity.
