### ISSUE TITLE
[Question] use custom estimator to tackle imbalanced datasets

### ISSUE THREAD

**Issue by simonprovost** [LAMDA-NJU/Deep-Forest#101]
Hi All,

As I expressed previously in another post, I want to express my gratitude for your amazing research. I am delighted you found time in your library to deal with custom estimators. However, I am having difficulty with the following:

Assume I develop the following implementation (using imblearn) and obtain an AUROC score of 0.62:
```
model = BalancedRandomForestClassifier(random_state=global_seed_random_state,
                                       class_weight="balanced_subsample",
                                       n_jobs=-1,
                                       replacement=True,
                                       )

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
show_output(model, X_test, y_test, y_pred)


Classification_report:
              precision    recall  f1-score   support

           0       0.97      0.61      0.75       499
           1       0.08      0.63      0.14        27

    accuracy                           0.61       526
   macro avg       0.52      0.62      0.45       526
weighted avg       0.92      0.61      0.72       526

ROC AUC Score:
0.6204260372597047
```

According to the reviews I've been reading regarding your original paper, if we have good results with RF and other similar classifiers, it is worthwhile to attempt Deep Forest and as base learner the one that worked well. However, I attempted to use the custom estimators via the following implementation:

```
model = CascadeForestClassifier(
    random_state=global_seed_random_state,
)

main_estimators = [BalancedRandomForestClassifier(
    class_weight="balanced_subsample",
    n_jobs=-1,
    replacement=True,
    random_state=global_seed_random_state,
) for _ in range(2)]


diverse_estimators = [BalancedRandomForestClassifier(
    class_weight="balanced_subsample",
    n_jobs=-1,
    replacement=True,
    random_state=global_seed_random_state,
) for _ in range(2)]

estimators = main_estimators + diverse_estimators

# layer
model.set_estimator(estimators)
```
The findings, however, are 10% less impressive, with an AUROC of `0.555`. Note: Above, diverse estimators appears because I attempted to add ExtraTrees or XGBoost instead of a second set of BalancedRandomForestClassifiers. Could you please attempt to direct me in the proper direction? What did I do incorrectly? From your perspective, what type of diversified classifier should I use? Note 2: An AUROC above of 0.6 is quite promising for my current application.

Thank you very much for your help in advanced.
Great day,

**Comment by xuyxu** [comment]
Hi @simonprovost, is the dataset publicly available? If the answer is yes, I am willing to take a closer look ;-)

**Comment by simonprovost** [comment]
@xuyxu Unfortunately, because it is a medical application, the surgeon will not allow such data to be publicly available for the time being, I am very sorry. I could, however, tell you a little about it to inform you. It is severely imbalanced to begin with (class 0: 95%), (class 1: 5 %). Because we are addressing rare diseases, we have to face this constraint and must overcome it instead of adding more data that we could only get perhaps in the ten next year I do not really know. Each of our features are binarised. We have over 60 features (results of some one hot encoded feature that has been done during the ETA). Additionally, we looked to see if any missing values or other information was critical and nothing needed to be double-checked from that view. Data is ready, however, we only have 1600 rows of data. From a surgeon's standpoint, all of the features are critical; the only things that might not be as crucial to remove are the patient's age/gender and whether or not the patient has a smoking history. That's all I can do, I am sorry and I know it is maybe not that helpful but I tried.

Hope it will give you an idea, feel free to ask me more,
Cheers a lot for the help.

**Comment by simonprovost** [comment]
@xuyxu  Note: Several approaches for under/over sampling have been attempted, and the balanced random forest appears to be the best at the moment. I could provide you with a latex table listing all strategies we have attempted and their associated results for various metrics.

**Comment by xuyxu** [comment]
Thanks for your kind reply @simonprovost. The possible reason is that the cascade structure of deep forest may not be suited for the imbalanced dataset (which has not been extensively studied before, and needs more empirical evidence). Maybe you could try out another publicly available dataset used for imbalanced classification, and see if deep forest with multiple layers outperforms one single layer.

**Comment by simonprovost** [comment]
That is an intriguing beginning place. Do not you believe that increasing diversity would be beneficial? However, as a junior in the field yet, I am unsure of how diverse it should be or what type of base learner would help increase diversity. However, I have noticed this work that is a fork of your original DF paper: https://link.springer.com/article/10.1007/s00500-020-05279-8 Perhaps Dr. Gao has made the implementation available on Github? Perhaps instead of the SMOTE enhancement, we could simply copy the same implementation and use it to execute an under sampler of the user's choice (dynamic Python parameter)? Do you have any idea if this paper has made any code available? If you have one, could you please share it with us here? If not, could I inquire as to why? Additionally, if you have any suggestions/ideas, I would appreciate hearing them.

Thank you so much for your assistance; it is extremely beneficial. Note: I completed a DF study for another uni. assignment and am currently working on a medium-length article regarding our findings that DF and a small quantity of data perform significantly better than a vanilla ML model! Thus, while imbalanced appears to be a constraint on the current DF implementation here, it appears to have been addressed by Dr. Gao and Dr. Wang in the study I referenced above. What are your thoughts?

Have a great day @xuyxu ,
Simon.

**Comment by xuyxu** [comment]
> Do you have any idea if this paper has made any code available? If you have one, could you please share it with us here? If not, could I inquire as to why? Additionally, if you have any suggestions/ideas, I would appreciate hearing them.

I am sorry, but we are not familiar with the authors of this paper. Maybe you could directly make contact with the corresponding author, and ask if they could provide you with the code.

> Note: I completed a DF study for another uni. assignment and am currently working on a medium-length article regarding our findings that DF and a small quantity of data perform significantly better than a vanilla ML model! Thus, while imbalanced appears to be a constraint on the current DF implementation here, it appears to have been addressed by Dr. Gao and Dr. Wang in the study I referenced above. What are your thoughts?

I am a little confused about the statement "DF and a small quantity of data perform significantly better than a vanilla ML model", what kind of ML model are you referring to?

If it indicates the vanilla deep forest model, then your study is about an improved version of deep forest (e.g., through changing the model structure or the type of base learner), or tasks like pre-training the deep forest (a counterpart of pre-training the neural network)?

**Comment by simonprovost** [comment]
> I am sorry, but we are not familiar with the authors of this paper. Maybe you could directly make contact with the corresponding author, and ask if they could provide you with the code.

My complete blunder I believe it was too late yesterday and thus assumed it was a publication by the same university's team. However, it is not; I will contact them and respond to you on this post in order to assist any other comers, but we could close the issue nevertheless.

> I am a little confused about the statement "DF and a small quantity of data perform significantly better than a vanilla ML model", what kind of ML model are you referring to?  If it indicates the vanilla deep forest model, then your study is about an improved version of deep forest (e.g., through changing the model structure or the type of base learner), or tasks like pre-training the deep forest (a counterpart of pre-training the neural network)?

I believe the phrase "vanilla" was misconstrued on my part. What I meant is that the Deep Forest (your implementation) with a base learner such as an XGBoost performed better than the XGBoost alone on another type of data I am working on, which is slightly imbalanced but not significantly so, and thus the DF copes well. However, I have just written about the results that confirm your original paper points. Nonetheless, there is no improvement of your implementation ye but the findings of the research I referenced above appear to significantly improve the existing implementation for imbalance datasets only, which is intriguing. It could be fascinating if they put up their implementation to the open-source community; I will investigate.

Thank you very much for your time and effort to help with my issue, I appreciate it. have a great week Dr Jianxin Wu. _Note: You could close the ticket if you wish, there is nothing to do anymore._

**Comment by xuyxu** [comment]
Thanks for your great work @simonprovost, hoping to see your publication in the near feature ;-)
