### ISSUE TITLE
can't get the features importance, please provide an example.

### ISSUE THREAD

**Issue by JohnTaco93** [LAMDA-NJU/Deep-Forest#104]
#code:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.base import clone
from deepforest import CascadeForestRegressor
import xgboost as xgb
import lightgbm as lgb

X, y = load_boston(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
model = CascadeForestRegressor(random_state=1)
model.get_layer_feature_importances(int(0))

#error
RuntimeError                              Traceback (most recent call last)
[<ipython-input-5-281407aaf0b5>](https://localhost:8080/#) in <module>()
     10 X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
     11 model = CascadeForestRegressor(random_state=1)
---> 12 model.get_layer_feature_importances(int(0))

[/usr/local/lib/python3.7/dist-packages/deepforest/cascade.py](https://localhost:8080/#) in get_layer_feature_importances(self, layer_idx)
   1118                 " importances property for each cascade layer."
   1119             )
-> 1120             raise RuntimeError(msg)
   1121         layer = self._get_layer(layer_idx)
   1122         return layer.feature_importances_

RuntimeError: Please use the sklearn backend to get the feature importances property for each cascade layer.

**Comment by xuyxu** [comment]
Hi @JohnTaco93 , in order to get feature importance, please use `model = CascadeForestRegressor(random_state=1, backend='sklearn')`. The functionality of feature importance is discarded for the sake of memory efficiency when using the default backend `custom`.

More info is available at https://deep-forest.readthedocs.io/en/latest/api_reference.html#deepforest.CascadeForestRegressor

**Comment by JohnTaco93** [comment]
Hello, thanks! it worked!
