### ISSUE TITLE
Matrix as an input of CascadeForestClassifier

### ISSUE THREAD

**Issue by JohnTaco93** [LAMDA-NJU/Deep-Forest#105]
I am working with multivariate time series classification and would like to work with the raw data as the input of the deep forest model. I think it should be similar to the 1D CNN in which the input, in my case, is a matrix of [1643x1250x3]. This means that I have 1643 samples and each sample is a matrix of 1250x3. I want to do the same with deep forest but when I use the cascade classifier I get the following error: too many values to unpack (expected 2). When the input is a simple vector, it works, like in normal machine learning problems for tabular data. I think there should be a way to do this task since in the previous documentation (gcforest) there is an example with images in which the input is a 2D matrix (mnist dataset). Please let me know if you have an example of this case with Deep Forest. 
Thanks!

**Comment by xuyxu** [comment]
Hi, @JohnTaco93, this version of deep forest focuses on tabular data only. For time series data, one possible solution is to first use feature extraction techniques (e.g., [tsfresh](https://tsfresh.readthedocs.io/en/latest/text/introduction.html)) to transform your data into a non-ordinal dataset (`[1643x1250x3] -> [1643, N]`, `N` the number of features generated by tsfresh).

**Comment by xuyxu** [comment]
Closed due to inactivity
