### ISSUE TITLE
Error in feature importance acquisition

### ISSUE THREAD

**Issue by shawzw** [LAMDA-NJU/Deep-Forest#106]
![image](https://user-images.githubusercontent.com/49910555/169842811-1d540ebe-8340-47de-bda8-60ed331af109.png)
CascadeForestRegressor: model.get_layer_feature_importances(0)
Error: Please use the sklearn backend to get the feature importances property for each cascade layer.

"This method is only applicable when deep forest is built using the sklearn backend" I'm not quite sure what that means

Thank you very much for answering my questions in your busy schedule!

**Comment by xuyxu** [comment]
Hi @shawzw, please set `backend="sklearn"` when instantiating the model, more details avaiable at https://deep-forest.readthedocs.io/en/latest/api_reference.html#deepforest.CascadeForestClassifier

**Comment by xuyxu** [comment]
Closed.
