### ISSUE TITLE
Does the package already support Multi-Grained Scanning as the old package gcForest?

### ISSUE THREAD

**Issue by PowderL** [LAMDA-NJU/Deep-Forest#107]
I didn't find any parameters related to the **Multi-Grained Scanning** operation. So, does the package already support Multi-Grained Scanning as the old package [gcForest](https://github.com/kingfengji/gcForest)?

Beyond this, I have a question related to the model training process. **Multi-Grained Scanning** generates a bag of instances for each original sample by sliding the window on the original feature vectors. Were the obtained bag of instances treated equally? That means the bag of instances was input to train a Forest Model simultaneously or was separately input to train different Forest Models. As the window slides on the original feature vectors, the obtained subfeature vectors were different from each other. Thus, should separating the bag of instances to train different Forest Models be more reasonable？

**Comment by xuyxu** [comment]
> I didn't find any parameters related to the Multi-Grained Scanning operation

Please read the start of README.md for details.

> Were the obtained bag of instances treated equally? That means the bag of instances was input to train a Forest Model simultaneously or was separately input to train different Forest Models.

The latter one.

**Comment by PowderL** [comment]
> > I didn't find any parameters related to the Multi-Grained Scanning operation
> 
> Please read the start of README.md for details.
> 
> > Were the obtained bag of instances treated equally? That means the bag of instances was input to train a Forest Model simultaneously or was separately input to train different Forest Models.
> 
> The latter one.

Is that mean **Multi-Grained Scanning** is not suitable for tabular data?

**Comment by PowderL** [comment]
Ok, thanks for your reply.
