### ISSUE TITLE
cannot import name 'CascadeForestRegressor' from 'deepforest'

### ISSUE THREAD

**Issue by sjjsjsb** [LAMDA-NJU/Deep-Forest#114]

**Comment by xuyxu** [comment]
Hi @sjjsjsb, what's your version of deep-forest?

**Comment by Kathy0217** [comment]
Hello,I have the same problem. My deepforest version is 0.1.6

**Comment by xuyxu** [comment]
@Kathy0217 Hi, what is your numpy version?

**Comment by xuyxu** [comment]
This looks like a problem when building wheels. For a quick solution, I would suggest you to install the package from source, please follow the instructions [here](https://deep-forest.readthedocs.io/en/latest/installation_guide.html#building-from-source). We will figure out how to improve the compatibility of the wheel ASAP.

**Comment by Kathy0217** [comment]
> @Kathy0217 Hi, what is your numpy version?

Thank you so much. I have already solved the problem.

**Comment by xuyxu** [comment]
Closed due to inactivity.
