### ISSUE TITLE
pip install deep-forest ERROR: Could not find a version that satisfies the requirement deep-forest (from versions: none)

### ISSUE THREAD

**Issue by hfraga-utad** [LAMDA-NJU/Deep-Forest#125]
Cannot install via pip

pip install deep-forest
ERROR: Could not find a version that satisfies the requirement deep-forest (from versions: none)

**Comment by xuyxu** [comment]
@hfraga-utad Hi, what is your python version?

**Comment by hfraga-utad** [comment]
sorry i was using python 3.11, with 3.9 works
