### ISSUE TITLE
np.int has been removed in munpy 1.24

### ISSUE THREAD

**Issue by Dmayset** [LAMDA-NJU/Deep-Forest#126]
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
  https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

`I found np.int in forest.py line 203 and line 566`

**Comment by Alberto199810** [comment]
Even if the np.int does not appear anymore in code, I got the same error even after upgrading the package (using deep_forest-0.1.7-cp38-cp38-manylinux2010_x86_64.whl)

**Comment by JueFeiH** [comment]
Is this problem solved?

**Comment by wuwangchuzhong12** [comment]
pip install python3.9

**Comment by 667w** [comment]
> 点安装Python3.9

I tried, but it didn't work.

**Comment by Karlheinzniebuhr** [comment]
Same issue here after a fresh pip install on python 3.9.18:

```
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
```
