### ISSUE TITLE
What is the `model.get_later_feature_importance(0)` for? 

### ISSUE THREAD

**Issue by laprasear** [LAMDA-NJU/Deep-Forest#128]
Hi, I want to know what is the `model.get_later_feature_importance(0)` used for, because I find the result of the above code is different from the SHAP, I wonder which one can I trust to explain the feature importance.

**Comment by xuyxu** [comment]
Hi, @laprasear, `get_layer_feature_importance` calls the native sckit-learn api, here is a brief introduction [URL](https://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances.html). It measures the importance of each feature from the perspective of **which feature is more discriminative (via measuring the degree to which it could improve the splitting gain)**.

I am not quite familiar with shapley value, but I think both could explain the feature importance as long as the underlying motivation makes sense.

**Comment by laprasear** [comment]
Thank you for your response!!!

I am also curious about the purpose of the **_binner_** in the model. Is it used to select certain features as split candidates in tree building? If that is the case, can I use all features as candidates?

Any assistance or guidance that you can provide would greatly help me in resolving the issues I am facing while working with DF in my work😁.

**Comment by xuyxu** [comment]
When building trees, binner is used to reduce the number of candidate splitting points for continuous features, which could greatly reduce training time costs. In most cases, there is no need to enumerate all distinct value in a continuous feature. Using binner for discretization and select one splitting value that is relatively good should be enough, since downstream tree nodes would further improve the generalization performance.

**Comment by laprasear** [comment]
Thank you for your kind reply. One more simple question, I am confused about this sentence in your [documentation:](https://deep-forest.readthedocs.io/en/stable/advanced_topics/architecture.html) "Bin the out-of-bag predictions of the previous cascade layer (denoted by augmented features in the figure above) using a newly-fitted binner." Does it mean that the out-of-bag predictions (y_predict?) from the previous layer are added as augmented features to the training samples (x_train) in the next cascade?

**Comment by xuyxu** [comment]
> Does it mean that the out-of-bag predictions (y_predict?) from the previous layer are added as augmented features to the training samples (x_train) in the next cascade?

Yes.

**Comment by laprasear** [comment]
Thank you for your help! Your kindness and patience in clarifying my confusions are truly appreciated.
