### ISSUE TITLE
module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by XingfuXu** [LAMDA-NJU/Deep-Forest#134]
My python version is 3.8 on a Mac OS. I use "pip install deep-forest" to install the module on my Mac successfully. However, when i ran the codes below:
    deep_forest = CascadeForestRegressor(random_state=1, verbose=0)
    deep_forest.fit(X, y)
I encountered the following error:

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Anyone could help? Thanks in advance.

**Comment by XingfuXu** [comment]
I also met another error:
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'

**Comment by WangJiuming** [comment]
Hi, I've just encountered exactly the same error after `pip install deep-forest` in a python=3.8 environment. I was able to fix the `np.int` error manually but the `np.bool` error seems to be hard to fix from user side. 
I have also tried the following:
1. downgrade numpy to 1.19 (<1.20), but the following error would occur:
```File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
2. build from scratch with `python setup.py install`, but the following error would occur:
```
Error compiling Cython file:
------------------------------------------------------------
...
    if not is_samples_sorted[0]:
        n_samples = end - start
        memcpy(sorted_samples + start, samples + start,
               n_samples * sizeof(SIZE_t))
        qsort(sorted_samples + start, n_samples, sizeof(SIZE_t),
              compare_SIZE_t)
              ^
------------------------------------------------------------

deepforest/tree/_splitter.pyx:1040:14: Cannot assign type 'int (const void *, const void *) except? -1 nogil' to 'int (*)(const void *, const void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (const void *, const void *) except? -1 nogil'.
```
Is there any way to solve this since this issue has been recently closed as completed? Thanks in advance!

**Comment by WangJiuming** [comment]
Solved by reinstalling `cpython==0.29.14` and building from scratch.

**Comment by Karlheinzniebuhr** [comment]
> Hi, I've just encountered exactly the same error after `pip install deep-forest` in a python=3.8 environment. I was able to fix the `np.int` error manually but the `np.bool` error seems to be hard to fix from user side. I have also tried the following:
> 
> 1. downgrade numpy to 1.19 (<1.20), but the following error would occur:
> 
> ```
> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
> ```
> 
> 2. build from scratch with `python setup.py install`, but the following error would occur:
> 
> ```
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
>     if not is_samples_sorted[0]:
>         n_samples = end - start
>         memcpy(sorted_samples + start, samples + start,
>                n_samples * sizeof(SIZE_t))
>         qsort(sorted_samples + start, n_samples, sizeof(SIZE_t),
>               compare_SIZE_t)
>               ^
> ------------------------------------------------------------
> 
> deepforest/tree/_splitter.pyx:1040:14: Cannot assign type 'int (const void *, const void *) except? -1 nogil' to 'int (*)(const void *, const void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (const void *, const void *) except? -1 nogil'.
> ```
> 
> Is there any way to solve this since this issue has been recently closed as completed? Thanks in advance!

could you please share your solution to the np.int error ? I'm getting the same issue:
```
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
```

**Comment by WangJiuming** [comment]
Hi Karl, my solution is to download the source code from this repo and run `python setup.py install` to build the package from scratch.
