### ISSUE TITLE
Set up the pre-commit workflow for automatic formatting on code style

### ISSUE THREAD

**Issue by tczhao** [LAMDA-NJU/Deep-Forest#15]
Maybe we can add a formatter like black in the Makefile and gitaction to make life easier for developer.
What do you think?

**Comment by xuyxu** [comment]
I thinks this is reasonable since many open source project uses the black coding style. Is it able to incorporate the black formatter in our `code-quality` CI? The ideal case in my mind is that the CI server will automatically conduct the formatting and flake8 checking.

**Comment by tczhao** [comment]
We can add it to CI, we have that in our private repo in bitbucket, should be similar.
Additionally, we can leverage pre-commit to help us format codes before commit
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by xuyxu** [comment]
Sounds great, I would appreciate it very much if you could set the pre-commit workflow for this project :-)

**Comment by tczhao** [comment]
Sure, will work on it at the weekend

**Comment by xuyxu** [comment]
Let me know if you need any help
