### ISSUE TITLE
.fit() not working when dataset contains bool variables

### ISSUE THREAD

**Issue by ianforme** [LAMDA-NJU/Deep-Forest#19]
I have a dataset with ~500 variables. Some are boolean variables. I had these error when try to fit the model 

`TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

And when I fit the model without these boolean variables, it worked.

**Comment by xuyxu** [comment]
Hi, thanks for the issue! Could you provide more traceback information so that I can locate where goes wrong

**Comment by ianforme** [comment]
3 for X_train, X_test, y_train, y_test in tqdm(dfs):
----> 4     model.fit(X_train.values, y_train.values)
      5 
      6     preds = model.predict_proba(X_test)[:,1]

~\Anaconda3\envs\ndd\lib\site-packages\deepforest\cascade.py in fit(self, X, y)
    437 
    438         # Bin the training data
--> 439         X_train_ = self._bin_data(binner_, X, is_training_data=True)
    440         X_train_ = self.buffer_.cache_data(0, X_train_, is_training_data=True)
    441 

~\Anaconda3\envs\ndd\lib\site-packages\deepforest\cascade.py in _bin_data(self, binner, X, is_training_data)
    334         tic = time.time()
    335         if is_training_data:
--> 336             X_binned = binner.fit_transform(X)
    337         else:
    338             X_binned = binner.transform(X)

~\Anaconda3\envs\ndd\lib\site-packages\sklearn\base.py in fit_transform(self, X, y, **fit_params)
    688         if y is None:
    689             # fit method of arity 1 (unsupervised transformation)
--> 690             return self.fit(X, **fit_params).transform(X)
    691         else:
    692             # fit method of arity 2 (supervised transformation)

~\Anaconda3\envs\ndd\lib\site-packages\deepforest\_binner.py in fit(self, X)
    133             self.bin_subsample,
    134             self.bin_type,
--> 135             self.random_state,
    136         )
    137 

~\Anaconda3\envs\ndd\lib\site-packages\deepforest\_binner.py in _find_binning_thresholds(X, n_bins, bin_subsample, bin_type, random_state)
     83             X[:, f_idx],
     84             n_bins,
---> 85             bin_type
     86         )
     87         binning_thresholds.append(threshold)

~\Anaconda3\envs\ndd\lib\site-packages\deepforest\_binner.py in _find_binning_thresholds_per_feature(col_data, n_bins, bin_type)
     35         raise RuntimeError(msg.format(len(col_data.shape)))
     36 
---> 37     missing_mask = np.isnan(col_data)
     38     if missing_mask.any():
     39         col_data = col_data[~missing_mask]

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by xuyxu** [comment]
Thanks! Another question is that what is the data type of your input to the model `X_train.values`?

 I am going to check that whether `np.isnan` has problems on handling your data type.

**Comment by ianforme** [comment]
X_train is a pandas dataframe with bool, float and integer data types. Thanks for the help

**Comment by xuyxu** [comment]
I think the problem is that `np.isnan` cannot properly handle the array of `X_train.values`, which is an array of the type `object` because of the mixed data types in the dataframe.

Can you verify that if using the following casting methods instead of directly calling `model.fit(X_train.values, y_train.values)` works:

```
casted_X_train, casted_X_test = X_train.to_numpy(dtype=np.float), X_test.to_numpy(dtype=np.float)
model.fit(casted_X_train, y_train.values)

preds = model.predict_proba(casted_X_test )[:,1]
```

The data type used internally is always `np.uint8`, and I think temporaily casting all elements into the data type `np.float` is fine.

**Comment by xuyxu** [comment]
Closed due to inactivity.
