### ISSUE TITLE
Buffer dtype mismatch

### ISSUE THREAD

**Issue by Mr-memorandum** [LAMDA-NJU/Deep-Forest#20]
调用数据集训练出现错误：
 File "deepforest/_cutils.pyx", line 59, in deepforest._cutils._map_to_bins
  File "deepforest/_cutils.pyx", line 76, in deepforest._cutils._map_to_bins
ValueError: Buffer dtype mismatch, expected 'const X_DTYPE_C' but got 'long'

**Comment by xuyxu** [comment]
Hi @Mr-memorandum, thanks for reporting! It looks like the binner cannot handle your input data properly.

What is the type and size of your input data? If your input data is a numpy array, you can use `data.dtype` and `data.shape` to get the answer.

**Comment by Mr-memorandum** [comment]
> Hi @Mr-memorandum, thanks for reporting! It looks like the binner cannot handle your input data properly.
> 
> What is the type and size of your input data? If your input data is a numpy array, you can use `data.dtype` and `data.shape` to get the answer.

thanks for your help, by using ``data.dtype`` and `` data.shape``, the return value is this :
<class 'numpy.ndarray'>
(7813, 15)
int64

**Comment by xuyxu** [comment]
We should support more data types. For now, you can use `data = data.astype(np.float)` before calling `fit` to avoid the problem.

Thanks for reporting! I will mark it as a feature request ;-)

**Comment by xuyxu** [comment]
Hi @Mr-memorandum, the version 0.1.1 should fix this issue.

Thanks for reporting, and feel free to open another issue if you still have any problem ;-)

**Comment by xuyxu** [comment]
closed via pr #23

**Comment by xuyxu** [comment]
@all-contributors please add @Mr-memorandum for bug
