### ISSUE TITLE
Custom CascadeForestClassifier

### ISSUE THREAD

**Issue by Maryom** [LAMDA-NJU/Deep-Forest#26]
Hey,

Thanks for your awesome repo.

I have a question if you don't mind could you please give me an example on how to change RandomForestClassifier and ExtraTreesClassifier in the CascadeForestClassifier?

**Comment by xuyxu** [comment]
Hi @Maryom, thanks for the issue. In order to change the base estimator and get it work, here are three steps you need to do:

* you need to include it in the `deepforest/_estimator.py`, and the class of your estimator should implement some basic methods on training and evaluating, such as `fit`, `predict`, `predict_proba`.
* you should check that whether your estimator supports **out-of-bag estimation**, which is a characteristic of forest estimator. If the answer is No, you have to use the origianl cross validation to generate class vectors in deep forest. Here is a good example on how to combine your estimator and cross validation: [KFlodWrapper](https://github.com/kingfengji/gcForest/blob/master/lib/gcforest/estimators/kfold_wrapper.py).
* you need to build the package from source, please follow the steps in [Build from Source](https://deep-forest.readthedocs.io/en/latest/installation_guide.html#building-from-source).

Using custom base estimator requires some extra works, I will keep this issue open, and let me know if you have any problem ;-)

**Comment by Maryom** [comment]
Thanks @xuyxu for your help I appreciate it. I need to add `XGBoost` I will try with it.

I have one more question if you don't mind: in the code is there a way to access `Multi-Grained Scanning`?

**Comment by xuyxu** [comment]
> Thanks @xuyxu for your help I appreciate it. I need to add `XGBoost` I will try with it.
> 
> I have one more question if you don't mind: in the code is there a way to access `Multi-Grained Scanning`?

If these are what you want, you can try out the original implementation: [gcForest](https://github.com/kingfengji/gcForest), it already has the `XGBoost` estimator and multi-grained scanner implemented. The purpose of this repo is to provide an time and memory efficient implementation of deep forest, mainly for tabular datasets. We are currently working on the scanner (PR #17), but there is still a long way to go.

**Comment by Maryom** [comment]
Great thank you so much

**Comment by xuyxu** [comment]
feel free to reopen the issue if you have any other problem ;-)

**Comment by Maryom** [comment]
Thank you so much I appreciate it. I added `XGBClassifier` successfully but if you don't mind can I tell you the changes I did? I wanna double check with you please.

Here are the changes:
In `deepforest/forest.py` I added the following:

```
__all__ = ["RandomForestClassifier", "ExtraTreesClassifier", "XGBClassifier"]

from xgboost import XGBClassifier

class XGBClassifier(ForestClassifier):
    @_deprecate_positional_args
    def __init__(
        self,
        n_estimators=100,
        *,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        n_jobs=None,
        random_state=None,
        verbose=0,
        max_samples=None
    ):
        super().__init__(
            base_estimator=ExtraTreeClassifier(),
            n_estimators=n_estimators,
            estimator_params=(
                "max_depth",
                "min_samples_split",
                "min_samples_leaf",
                "random_state",
            ),
            n_jobs=n_jobs,
            random_state=random_state,
            verbose=verbose,
            class_weight=class_weight,
            max_samples=max_samples,
        )

        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.min_samples_leaf = min_samples_leaf
```
In `deepforest/_estimator.py` I added the following:

```
from xgboost import XGBClassifier

# XGBClassifier
    elif name == "xgb":
        estimator = XGBClassifier(
            n_estimators=n_trees,
        )
    else:
        msg = "Unknown type of estimator, which should be one of {{rf, erf, xgb}}."
        raise NotImplementedError(msg)
```

**Comment by xuyxu** [comment]
Hi @Maryom, I think there is no need to create another class `XGBClassifier` in `forest.py` since we are going to use the `XGBClassifier` from the XGBoost package, right?

What's missing is the implementation on the `oob_decision_function_` property used in Line 62 of `_estimator.py`. To implement the idea, you should wrap the `XGBClassifier` with another class, for example `XGBClassifierWrapper`:

``` python
from xgboost import XGBClassifier
from sklearn.model_selection import KFold

class XGBClassifierWrapper(object):

    def __init__(self, n_outputs, n_splits, other_args_for_XGBClassifiers):
        self.n_outputs = n_outputs
        self.n_splits= n_splits

        self.estimators = []  # an internal container on XGBClassifiers
        for _ in range(self.n_folds):
            self.estimators.append(XGBClassifier(other_args_for_XGBClassifiers)

    def fit(self, X, y, sample_weight=None):
        n_samples = X.shape[0]
        kf = KFold(n_splits=self.n_splits)
        self.oob_decision_function_ = np.zeros((n_samples, self.n_outputs))

        # Fit XGBClassifiers
        for (train_idx, test_idx), xgb_model in zip(kf.split(X), self.estimators):
            xgb_model.fit(X[train_idx], y[train_idx])
            self.oob_decision_function_[test_idx] += xgb_model.predict_proba(X[test_idx])

    def predict_proba(self, X):
        n_samples = X.shape[0]
        proba = np.zeros((n_samples, self.n_outputs))
        for xgb_model in self.estimators:
            proba += xgb_model.predict_proba(X) / self.n_splits
```

In the code snippet above, we have replaced the out-of-bag estimation with cross validation. If you are confused about cross validation, you can check the Wikipedia page. Just keep in mind that out-of-bag estimation and cross validation are both effective ways to obtain class vectors used in deep forest. However, out-of-estimation is not a feature of XGBClassifier, and the only solution for XGBClassifier is cross validation.

 This code snippet is still very rough, feel free to comment below if you have any other question.

**Comment by Maryom** [comment]
Thank you so much this is really helpful. It worked but there is a missing `)` at the end of this line:
`self.estimators.append(XGBClassifier(other_args_for_XGBClassifiers)`

Thanks again 🙏🏼

**Comment by Maryom** [comment]
Hello again,

Sorry for bothering I need to check that `XGBClassifiers` is correctly added, because when I ran:
`xgb_forest = model.get_forest(0, 0, "xgb")`

I got the following error: 
```
"deepforest/cascade.py", line 1020, in get_forest
    raise ValueError(msg.format(forest_type))
ValueError: `forest_type` should be one of {rf, erf}, but got xgb instead.
```

Here the files I changed to add `XGBClassifiers`:
In `deepforest/_estimator.py` I added:
```
from xgboost import XGBClassifier

# XGBClassifier
    elif name == "xgb":
        estimator = XGBClassifier(
            n_estimators=n_trees,
        )
    else:
        msg = "Unknown type of estimator, which should be one of {{rf, erf, xgb}}."
        raise NotImplementedError(msg)


class XGBClassifierWrapper(object):

    def __init__(self, n_outputs, n_splits, other_args_for_XGBClassifiers):
        self.n_outputs = n_outputs
        self.n_splits= n_splits

        self.estimators = []  # an internal container on XGBClassifiers
        for _ in range(self.n_folds):
            self.estimators.append(XGBClassifier(other_args_for_XGBClassifiers))

    def fit(self, X, y, sample_weight=None):
        n_samples = X.shape[0]
        kf = KFold(n_splits=self.n_splits)
        self.oob_decision_function_ = np.zeros((n_samples, self.n_outputs))

        # Fit XGBClassifiers
        for (train_idx, test_idx), xgb_model in zip(kf.split(X), self.estimators):
            xgb_model.fit(X[train_idx], y[train_idx], sample_weight=sample_weight)
            self.oob_decision_function_[test_idx] += xgb_model.predict_proba(X[test_idx])

    def predict_proba(self, X):
        n_samples = X.shape[0]
        proba = np.zeros((n_samples, self.n_outputs))
        for xgb_model in self.estimators:
            proba += xgb_model.predict_proba(X) / self.n_splits
```

In `deepforest/forest.py` I added:

```
__all__ = [
    "RandomForestClassifier",
    "RandomForestRegressor",
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "XGBClassifier",
    "XGBClassifier",
]
```

Did I miss something?

**Comment by xuyxu** [comment]
Hi @Maryom, you should further change the method [get_forest](https://github.com/LAMDA-NJU/Deep-Forest/blob/master/deepforest/cascade.py#L974) in `cascade.py` if you are interested in a single base estimator. The current implementation of the `get_forest` method is incompatible with customized base estimators.

**Comment by Maryom** [comment]
Hey @xuyxu Thanks 🙏🏼 I changed it and I got the following error:

```
line 1025, in get_forest
    estimator = layer.estimators_[est_key]
KeyError: '0-0-xgb'
```

**Comment by xuyxu** [comment]
> Hey @xuyxu Thanks 🙏🏼 I changed it and I got the following error:
> 
> ```
> line 1025, in get_forest
>     estimator = layer.estimators_[est_key]
> KeyError: '0-0-xgb'
> ```

Could you print out the keys and values of the dictionary `layers.estimators`?

**Comment by Maryom** [comment]
Here are:

```
{'0-0-rf': <deepforest._estimator.Estimator object at 0x12f81a5e0>, '0-1-rf': <deepforest._estimator.Estimator object at 0x12f81a9d0>, '0-0-erf': <deepforest._estimator.Estimator object at 0x12f8514c0>, '0-1-erf': <deepforest._estimator.Estimator object at 0x12f8c40a0>}
```
It seems XGBoost is NOT there, could you please guide me where else I have to modify the code?

**Comment by xuyxu** [comment]
Try set the forest_type of 'get_forest' as either 'rf' or 'erf', I think the result is your xgb estimator :-)

**Comment by Maryom** [comment]
I already check it here:

```
if forest_type not in ("rf", "erf", "xgb"):
            msg = (
                "`forest_type` should be one of {{rf, erf}},"
                " but got {} instead."
            )
            raise ValueError(msg.format(forest_type))
```

I have a question if you don't mind: why `layers.estimators` just has four forest, although I added: 
```
__all__ = [
    "RandomForestClassifier",
    "RandomForestRegressor",
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "XGBClassifier",
    "XGBClassifier",
]
```

**Comment by xuyxu** [comment]
You can check the use of `__all__` [here](https://stackoverflow.com/questions/44834/can-someone-explain-all-in-python). It does NOT have any effect on the number of base estimators in each cascade layer. You can change the value of `n_estimators` (default is 2) in order to change the number of base estimators in each layer.

**Comment by Maryom** [comment]
Thanks 🙏🏼 but I don't need to change the number of estimators. I need to add `XGBClassifier`.

Why `XGBClassifier` is NOT in the dictionary `layers.estimators`?

**Comment by xuyxu** [comment]
Could you open source your code after modification as a personal Repo and link it here, so that I can take a careful look ;-)

**Comment by Maryom** [comment]
Here is [the repo.](https://github.com/Maryom/DF21.git) Thanks for your help I appreciate it 🙏🏼

**Comment by xuyxu** [comment]
Hi @Maryom, sorry for my late response. Could you further upload a running script in the root directory, so that I can better understand the entire workflow ;-)

**Comment by Maryom** [comment]
It's totally fine I really appreciate your help 🙏🏼 Kindly check [the repo.](https://github.com/Maryom/DF21) I added: `tests/test_xgb.py`

**Comment by xuyxu** [comment]
Hi @Maryom, please check our latest PR #48 ;-)

**Comment by zhuang-hao-ming** [comment]
> > Thanks @xuyxu for your help I appreciate it. I need to add `XGBoost` I will try with it.
> > I have one more question if you don't mind: in the code is there a way to access `Multi-Grained Scanning`?
> 
> If these are what you want, you can try out the original implementation: [gcForest](https://github.com/kingfengji/gcForest), it already has the `XGBoost` estimator and multi-grained scanner implemented. The purpose of this repo is to provide an time and memory efficient implementation of deep forest, mainly for tabular datasets. We are currently working on the scanner (PR #17), but there is still a long way to go.

Hello @xuyxu , Is the functionality of scanner same as multi-grained scanner in the paper? It seems that it is available now.

**Comment by xuyxu** [comment]
> > > Thanks @xuyxu for your help I appreciate it. I need to add `XGBoost` I will try with it.
> > > I have one more question if you don't mind: in the code is there a way to access `Multi-Grained Scanning`?
> > 
> > 
> > If these are what you want, you can try out the original implementation: [gcForest](https://github.com/kingfengji/gcForest), it already has the `XGBoost` estimator and multi-grained scanner implemented. The purpose of this repo is to provide an time and memory efficient implementation of deep forest, mainly for tabular datasets. We are currently working on the scanner (PR #17), but there is still a long way to go.
> 
> Hello @xuyxu , Is the functionality of scanner same as multi-grained scanner in the paper? It seems that it is available now.

Thanks for your interests @zhuang-hao-ming. No, there is still a long way to go before supporting the scanner part. Please refer to the original repo if you want to use the scanner part for now.

**Comment by xuyxu** [comment]
Closed via #48.

**Comment by zhuang-hao-ming** [comment]
> > > > Thanks @xuyxu for your help I appreciate it. I need to add `XGBoost` I will try with it.
> > > > I have one more question if you don't mind: in the code is there a way to access `Multi-Grained Scanning`?
> > > 
> > > 
> > > If these are what you want, you can try out the original implementation: [gcForest](https://github.com/kingfengji/gcForest), it already has the `XGBoost` estimator and multi-grained scanner implemented. The purpose of this repo is to provide an time and memory efficient implementation of deep forest, mainly for tabular datasets. We are currently working on the scanner (PR #17), but there is still a long way to go.
> > 
> > 
> > Hello @xuyxu , Is the functionality of scanner same as multi-grained scanner in the paper? It seems that it is available now.
> 
> Thanks for your interests @zhuang-hao-ming. No, there is still a long way to go before supporting the scanner part. Please refer to the original repo if you want to use the scanner part for now.

Thanks for your response. Is it possible that i use the original repo for getting multi-grain feature. and use these feature in this new repo for training?

**Comment by xuyxu** [comment]
> > > > > Thanks @xuyxu for your help I appreciate it. I need to add `XGBoost` I will try with it.
> > > > > I have one more question if you don't mind: in the code is there a way to access `Multi-Grained Scanning`?
> > > > 
> > > > 
> > > > If these are what you want, you can try out the original implementation: [gcForest](https://github.com/kingfengji/gcForest), it already has the `XGBoost` estimator and multi-grained scanner implemented. The purpose of this repo is to provide an time and memory efficient implementation of deep forest, mainly for tabular datasets. We are currently working on the scanner (PR #17), but there is still a long way to go.
> > > 
> > > 
> > > Hello @xuyxu , Is the functionality of scanner same as multi-grained scanner in the paper? It seems that it is available now.
> > 
> > 
> > Thanks for your interests @zhuang-hao-ming. No, there is still a long way to go before supporting the scanner part. Please refer to the original repo if you want to use the scanner part for now.
> 
> Thanks for your response. Is it possible that i use the original repo for getting multi-grain feature. and use these feature in this new repo for training?

I think this should work since the scanner and cascade forest part are decoupled ([See Here](https://github.com/kingfengji/gcForest/blob/master/lib/gcforest/gcforest.py#L24)). I will appreciate your feedback very much if you are going to try out this pipeline ;-)

**Comment by zhuang-hao-ming** [comment]
> > > > > > Thanks @xuyxu for your help I appreciate it. I need to add `XGBoost` I will try with it.
> > > > > > I have one more question if you don't mind: in the code is there a way to access `Multi-Grained Scanning`?
> > > > > 
> > > > > 
> > > > > If these are what you want, you can try out the original implementation: [gcForest](https://github.com/kingfengji/gcForest), it already has the `XGBoost` estimator and multi-grained scanner implemented. The purpose of this repo is to provide an time and memory efficient implementation of deep forest, mainly for tabular datasets. We are currently working on the scanner (PR #17), but there is still a long way to go.
> > > > 
> > > > 
> > > > Hello @xuyxu , Is the functionality of scanner same as multi-grained scanner in the paper? It seems that it is available now.
> > > 
> > > 
> > > Thanks for your interests @zhuang-hao-ming. No, there is still a long way to go before supporting the scanner part. Please refer to the original repo if you want to use the scanner part for now.
> > 
> > 
> > Thanks for your response. Is it possible that i use the original repo for getting multi-grain feature. and use these feature in this new repo for training?
> 
> I think this should work since the scanner and cascade forest part are decoupled ([See Here](https://github.com/kingfengji/gcForest/blob/master/lib/gcforest/gcforest.py#L24)). I will appreciate your feedback very much if you are going to try out this pipeline ;-)

It seems that is is difficult to directly integrate the scanner from gcForest with the cascade forest in Deep-Forest. When considering multi-grain features, the trainning data is composed of current feature and different level feature from scanner.

**Comment by xuyxu** [comment]
Thanks for reporting @zhuang-hao-ming. From my point of view, it is somehow weird to use tree-based methods on structured datasets like images, since it is not likely that they could perform better than CNNs. Besides, the starting point of this repo is to develop an efficienct version of deep forest for **tabular datasets**. As far as I know, none of existing tree-based methods is equipped with additional stages on handling structured data.

**Comment by zhuang-hao-ming** [comment]
@xuyxu Thanks for your response. 
Perhaps, when processing images data, it is a more reasonable choice to use CNN to extract features and then use deep forest for classification.

**Comment by xuyxu** [comment]
> @xuyxu Thanks for your response.
> Perhaps, when processing images data, it is a more reasonable choice to use CNN to extract features and then use deep forest for classification.

According to my experiments, using a CNN as a feature extractor in combination with a standalone predictor like deep forest is less effective than directly optimizing a CNN with a very simple clasifier appended (e.g., a linear layer plus softmax normalization).
