### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by eladmw** [LAMDA-NJU/Deep-Forest#27]
Considering the number of aggregations from each model in each layer, it would be nice to train the models faster

**Comment by xuyxu** [comment]
Hi @eladmw, thanks for your suggestions.

Do you have any good material on the GPU forest? It would be impossible to implement the GPU version from scratch with our current workforce.

**Comment by eladmw** [comment]
Looks like there's many references to XGBRegressor, which has compatibility with GPUs. I skimmed so correct me if I'm wrong, but I think that you can do XGBRegressor(tree_method='gpu_hist', gpu_id=0), or feed the params into the training interface with a dict setting :
param['gpu_id'] = 0
param['tree_method'] = 'gpu_hist'

**Comment by xuyxu** [comment]
Thanks @eladmw!

I think the first step we need to take is to support customized base estimators in the layer (see issue #29). After then, we can make it compatiable with the GPU version of XGB model. Let's keep this issue open for a while ;-)

**Comment by xuyxu** [comment]
Closed via #14
