### ISSUE TITLE
Generic cascade structure

### ISSUE THREAD

**Issue by tczhao** [LAMDA-NJU/Deep-Forest#29]
Maybe at some point, we can refactor and allows user supplying custom models for the layers

**Comment by xuyxu** [comment]
Thanks for your suggestions. Any idea on how to make the feature easy-to-use?

The code snippet implements a wrapper for XGB model, which should also work if we want to use other models.

``` python
class XGBClassifierWrapper(object):

    def __init__(self, n_outputs, n_splits, other_args_for_XGBClassifiers):
        self.n_outputs = n_outputs
        self.n_splits= n_splits

        self.estimators = []  # an internal container on XGBClassifiers
        for _ in range(self.n_folds):
            self.estimators.append(XGBClassifier(other_args_for_XGBClassifiers)

    def fit(self, X, y, sample_weight=None):
        n_samples = X.shape[0]
        kf = KFold(n_splits=self.n_splits)
        self.oob_decision_function_ = np.zeros((n_samples, self.n_outputs))

        # Fit XGBClassifiers
        for (train_idx, test_idx), xgb_model in zip(kf.split(X), self.estimators):
            xgb_model.fit(X[train_idx], y[train_idx], sample_weight=sample_weight)
            self.oob_decision_function_[test_idx] += xgb_model.predict_proba(X[test_idx])

    def predict_proba(self, X):
        n_samples = X.shape[0]
        proba = np.zeros((n_samples, self.n_outputs))
        for xgb_model in self.estimators:
            proba += xgb_model.predict_proba(X) / self.n_splits
```

**Comment by py666888** [comment]
您好，请问如果我想自定义决策树的分裂指标，应该如何进行？

**Comment by py666888** [comment]
您好，请问我自定义n_estimators =2（默认），但是级联结构是两种森林组成，那么每一层就是4个森林。如果我把n_estimators =2（默认），use_predictor =True，predictor='XGBoost'，那么每一层的结构是只有2个XGboost吗？这样的话，假如我想级联2种自定义的分类器，应该怎么设置呢？

**Comment by py666888** [comment]
您好，请问我设置n_estimators =2（默认），由于级联结构每一层是两种森林组成，那么每一层就由4个森林。如果我把参数进行如下设置：n_estimators =2（默认），use_predictor =True，predictor='XGBoost'，那么每一层的结构是只有2个XGboost吗？如果这样的话，假如我想级联2种自定义的分类器，比如我想级联随机森林和XGBoot应该如何进行设置呢？还有一个问题，如果我想自定义决策树特征分裂的依据，应该在哪个地方进行修改，如何设置？非常感谢您的耐心答复

**Comment by py666888** [comment]
> 也许在某个时候，我们可以重构并允许用户为层提供自定义模型

你好，请问我设置n_estimators =2（默认），由于级联结构每一层是两种森林组成，那么每一层就由4个森林组成。如果我把参数设置如下：n_estimators =2（默认） ，use_predictor =True，predictor='XGBoost'，那么每一层的有2个XGboost吗？应该如何进行设置？还有一个问题，如果我想自定义决策树分支的论点，应该在哪个地方进行修改，如何？非常感谢您的支持答复设置呢？

**Comment by py666888** [comment]
> 感谢您的建议。关于如何使该功能易于使用的任何想法？
> 
> 代码片段为 XGB 模型实现了一个包装器，如果我们想使用其他模型，它也应该可以工作。
> 
> ```python
>  XGBClassifierWrapper类（对象）：
> 
>     def  __init__ ( self , n_outputs , n_splits , other_args_for_XGBClassifiers ):
>          self。n_outputs  =  n_outputs 
>         self。n_splits =  n_splits
> 
>         自我。estimators  = []   # XGBClassifiers 上的一个内部容器，
>         用于 _  in  range ( self . n_folds ):
>              self . 估计器。追加（XGBClassifier（other_args_for_XGBClassifiers）
> 
>     def  fit ( self , X , y , sample_weight = None ):
>          n_samples  =  X。形状[ 0 ]
>          KF  =  KFold（n_splits =自我。n_splits）
>         自我。oob_decision_function_  =  np。零(( n_samples , self . n_outputs ))
> 
>         # Fit XGBClassifiers 
>         for ( train_idx , test_idx ), xgb_model  in  zip ( kf . split ( X ), self . estimators ):
>              xgb_model . 拟合( X [ train_idx ], y [ train_idx ], sample_weight = sample_weight )
>              self。oob_decision_function_ [ test_idx ] +=  xgb_model。predict_proba ( X [ test_idx ])
> 
>     def  predict_proba ( self , X ):
>          n_samples  =  X。形状[ 0 ]
>          proba  =  np . 零（（N_SAMPLES次，自我。n_outputs））
>         为 xgb_model 的 自我。估计量：
>              proba  +=  xgb_model。predict_proba（X）/ 自我。n_splits
> ```


你好，请问我设置n_estimators =2（默认参数），由于级联结构每一层是两种森林组成，那么每一层就由4个森林组成。如果我把设置如下：n_estimators =2（默认） ，use_predictor =True，predictor='XGBoost'，那么每一层有2个XGboost吗？应该如何进行设置？还有一个问题，如果我想自定义决策树分支的论点，应该在地方进行修改，如何？非常感谢您的支持设置呢？

**Comment by py666888** [comment]
> 也许在某个时候，我们可以重构并允许用户为层提供自定义模型

我设置n_estimators =2（默认参数），论文中提到由于级联结构每一层是两种森林组成，那么每一层就是4个森林组成。如果我进行设置如下：n_estimators =2（默认） ，use_predictor =True，predictor='XGBoost'，那么级联结构中是只有一种分类器XGBoost，那么每一层的结构是只有2个XGboost吗？如果我想设置2个随机森林和2个XGBoost作为每一层的级联结构，应该如何进行设置？还有一个问题，如果我想自定义随机森林中的决策树特征分裂标准，应该在地方进行实现呢？

**Comment by py666888** [comment]
> 也许在某个时候，我们可以重构并允许用户为层提供自定义模型

我设置n_estimators =2（默认参数），论文中提到由于级联结构每一层是2种森林组成，那么每一层就是4个森林组成。如果我进行设置如下：n_estimators =2（默认） ，use_predictor =True，predictor='XGBoost'，那么级联结构中是只有一种分类器XGBoost，那么每一层的结构是只有2个XGboost吗？如果我想设置2个随机森林和2个XGBoost作为每一层的级联结构，应该如何进行设置？还有一个问题，如果我想自定义随机森林中的决策树特征分裂标准，应该在地方进行实现呢？
