### ISSUE TITLE
is there deep forest regressor?

### ISSUE THREAD

**Issue by JTang-qhzx** [LAMDA-NJU/Deep-Forest#3]

**Comment by xuyxu** [comment]
No, this version only supports binary and mutl-class classification.

Another `CascadeForestRegressor` should be easy to be plugged in, but it requires many modifications on the algorithmic-level.

**Comment by morestart** [comment]
can we have a timeline to support regressor?

**Comment by JTang-qhzx** [comment]
> No, this version only supports binary and mutli-class classification.
> 
> Another `CascadeForestRegressor` should be easy to be plugged in, but it requires many modifications on the algorithmic-level.

Thanks for your reply!It will be great to have a deep forest regressor like Scikit-learn.

**Comment by xuyxu** [comment]
That would be really nice @morestart ! Actually, there can be some problems on implementing the extension to regression. I will open another issue latter, and call you there ;-)

**Comment by xuyxu** [comment]
Closed via #4
