### ISSUE TITLE
can't install package use conda env

### ISSUE THREAD

**Issue by morestart** [LAMDA-NJU/Deep-Forest#32]
ERROR: Could not find a version that satisfies the requirement deep-forest (from versions: none)
ERROR: No matching distribution found for deep-forest

system: mac
python version: 3.8.5
pip version: 20.2.4

**Comment by xuyxu** [comment]
Did you use the command `pip install deep-forest`? This package is not available via `conda install deep-forest`

**Comment by morestart** [comment]
> Did you use the command `pip install deep-forest`? This package is not available via `conda install deep-forest`

yes , i use  pip to install this package, but i use conda create this env...

**Comment by xuyxu** [comment]
Thanks for reporting @morestart. Could you give me the command on creating the virtual environment, I will figure out if this problem is reproducible.

**Comment by morestart** [comment]
i create this env by pycharm project create

**Comment by xuyxu** [comment]
I think I know what's wrong, wheels for mac-os are not available yet, and you need to build the package from source. You can refer to this issue #6. Feel free to tell me if you have any problem on building the package from source.

**Comment by xuyxu** [comment]
Hi @morestart, we have uploaded the wheel for Mac-OS. Now you can install it via `pip install deep-forest`.

Feel free to reopen the issue if there is any problem ;-)

**Comment by morestart** [comment]
> Hi @morestart, we have uploaded the wheel for Mac-OS. Now you can install it via `pip install deep-forest`.
> 
> Feel free to reopen the issue if there is any problem ;-)

thanks very much!
