### ISSUE TITLE
Documentation is unable to access

### ISSUE THREAD

**Issue by bigrat911** [LAMDA-NJU/Deep-Forest#38]
Document like https://deep-forest.readthedocs.io/en/latest/how_to_get_started.html is not available

**Comment by xuyxu** [comment]
Hi @bigrat911, thanks for reporting! You should replace `latest` with `master`.

Besides, where did you find this link? We will give a proofread on the entire documentation and fix these links.

**Comment by xuyxu** [comment]
Closed due to inactivity.
