### ISSUE TITLE
Support `CascadeForestRegressor` for univariate and multivariate regression

### ISSUE THREAD

**Issue by xuyxu** [LAMDA-NJU/Deep-Forest#4]
The forest model excels at the regression problem, and tends to have a much smaller variance than GBDTs. Therefore, it would be nice if deep forest could further support univariate and multivariate regression.

**Related issue**
#3

**Possible steps on this feature request**

* [ ] Include `sklearn.RandomForestRegressor` to `sklearn.ExtraTreesRegressor` in `estimator.py`
* [ ] Implement a cascade layer for regression in `layer.py`
* [ ] Implement the `CascadeForestRegressor` in `cascade.py`
* [ ] Evaluate the performance of `CascadeForestRegressor`
* [ ] Add unit tests on all related parts

**Comment by xuyxu** [comment]
Hi @morestart, I have created the issue on implementing deep forest regressor. Feel free to comment below if you need any help.

**Comment by morestart** [comment]
thanks for your reply, i will watch this repo~

**Comment by xuyxu** [comment]
Closed via issue #14. Hi @morestart, let me know if you have made any progress. Supporting regression will be our central target recently, and we are willing to have more people join in ;-)
