### ISSUE TITLE
Error: could not allocate 0 bytes

### ISSUE THREAD

**Issue by zhenlingcn** [LAMDA-NJU/Deep-Forest#41]
When I was using this package, I experienced the following problem. According to my observation, there is still a lot of available memory. Thus, what's the problem?

```
  File "deepforest/tree/_tree.pyx", line 123, in deepforest.tree._tree.DepthFirstTreeBuilder.build
  File "deepforest/tree/_tree.pyx", line 256, in deepforest.tree._tree.DepthFirstTreeBuilder.build
  File "deepforest/tree/_tree.pyx", line 480, in deepforest.tree._tree.Tree._resize_node_c
  File "deepforest/tree/_utils.pyx", line 34, in deepforest.tree._utils.safe_realloc
MemoryError: could not allocate 0 bytes
```

**Comment by xuyxu** [comment]
Hi @zhenlingcn, thanks for reporting! Could you print out the data type and shape of your training data, so that we can reproduce the problem.

**Comment by zhenlingcn** [comment]
Yeah, it's very easy to reproduce this problem. We just need to run the following codes:
```python
import numpy as np
from deepforest import CascadeForestRegressor

c = CascadeForestRegressor(n_jobs=1, verbose=0)
c.fit(np.random.randn(10, 5), np.zeros(10, dtype=np.float32))
```

**Comment by zhenlingcn** [comment]
By the way, I want to point out that some other normal data has also raised this error.

**Comment by xuyxu** [comment]
Thanks @zhenlingcn, I can reproduce your problem. I will take a careful look latter.

**Comment by xuyxu** [comment]
This code snippet runs fine:

``` python
import numpy as np
from deepforest import CascadeForestRegressor

c = CascadeForestRegressor(n_jobs=1, verbose=2)
c.fit(np.random.randn(10, 5), np.random.randn(10,))
```

If you want to use DF21 on the fly, could you check if there is a problem after converting the type of `y_train` into `np.float64`.
We will check where goes wrong when using the target values of type `np.float32`.

**Comment by xuyxu** [comment]
@all-contributors please add @zhenlingcn for bug

**Comment by zhenlingcn** [comment]
I don't believe I can solve the problem by simply modifying the data type. In fact, in the given case, it will still raise an error even if we change the type of the data.

**Comment by xuyxu** [comment]
I agree. Besides, what is the result using the following command on your target values:

``` python
import numpy as np
from sklearn.utils.multiclass import type_of_target

print(type_of_target(y_train))
```

When `y_train` is `np.zeros(10, dtype=np.float32)`, the result is `binary`, which is not compatible with `CascadeForestRegressor`.

**Comment by xuyxu** [comment]
Hi @zhenlingcn, I will appreciate it if your could test whether the latest PR #44 raises the same error for your problem. The wheels are available at [here](https://github.com/LAMDA-NJU/Deep-Forest/actions/runs/591842537).

**Comment by zhenlingcn** [comment]
I don't believe the latest PR is an appropriate solution. For example, the following test case is a very reasonable test case. However, the latest version of Deep Forest will raise an error.
```python
import numpy as np
from deepforest import CascadeForestRegressor

c = CascadeForestRegressor(n_jobs=1, verbose=0)
c.fit(np.random.randn(10, 5), np.array([1, 2, 3, 4, 5]))
```

```
CascadeForestRegressor is used for univariate or multi-variate regression, but the target values seem not to be one of them.
```

**Comment by xuyxu** [comment]
Thanks for your feedback, will take a look at the Cython side when I get a moment.

**Comment by zhenlingcn** [comment]
In fact, this problem has hindered me to conduct several comparative experiments. I hope this problem can be solved as soon as possible.

**Comment by xuyxu** [comment]
Sorry for your problem. Could you check if using the sklearn backend works?

``` python
c = CascadeForestRegressor(backend="sklearn")
```

**Comment by zhenlingcn** [comment]
It's great! The sklearn backend seems to work well.

**Comment by xuyxu** [comment]
Glad to here that 😄

**Comment by 609347781** [comment]
ValueError: CascadeForestRegressor is used for univariate or multi-variate regression, but the target values seem not to be one of them.
您好我也遇到了这个问题，设置backend="sklearn"还是会报错，是不是我这边标签列只有0.1的原因（分类的代码可以正常运行）
以下我的数据读取部分
Data = pd.read_excel(r'D:\秭归-巴东段易发性基础数据\第二次实验\预测数据\整体数据.xlsx')
Feature = Data.iloc[1:578158,4:14].values
Label = Data.iloc[1:578158,1].values
print(Label)
print('数据已读取')
#-标准化处理
StandPFeature = preprocessing.StandardScaler().fit_transform(Feature)

#-------2.构造训练集和测试集------#
xTrain = StandPFeature[0:8660,:] #训练集特征
xTest = StandPFeature[len(xTrain):len(StandPFeature),:] #测试集特征
yTrain = Label[:8660:].ravel()
yTest = Label[len(xTrain):len(StandPFeature):].ravel()
print('训练集已分类完毕')
望解答，非常感谢！！！！！

**Comment by 609347781** [comment]
rf1 = CascadeForestRegressor(backend="sklearn")
rf1.fit(xTrain,yTrain)
pred_value=rf1.predict(xTest)

**Comment by xuyxu** [comment]
你好，数据集的标签列既然只有0、1取值，为啥要用`CascadeForestRegressor`?

**Comment by 609347781** [comment]
我也不想做回归的，但是这边后续用所得的概率是做一个地质方面的图，回归模型出的图好看一点（水paper），就用回归模型了

就如果是分类，把最后分类器的是哪一类的概率输出也行，但是我没找到怎么弄，分类器都封装好了...






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi-Xuan ***@***.***&gt;; 
发送时间: 2022年5月5日(星期四) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LAMDA-NJU/Deep-Forest] Error: could not allocate 0 bytes (#41)





 
你好，数据集的标签列既然只有0、1取值，为啥要用CascadeForestRegressor?

**Comment by xuyxu** [comment]
请尝试调用`CascadeForestClassifier`的`predict_proba`方法，它会返回每个样本属于正类的概率

**Comment by 609347781** [comment]
用sklearn里的随机森林模型也可以正常运行，之前的图就是用随机森林做的，0-1区间概率用绿红渐变色做一下图




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LAMDA-NJU/Deep-Forest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LAMDA-NJU/Deep-Forest] Error: could not allocate 0 bytes (#41)





 
你好，数据集的标签列既然只有0、1取值，为啥要用CascadeForestRegressor?

**Comment by 609347781** [comment]
thanks！

**Comment by GOD-TEN** [comment]
作者您好，我也有这个问题。我做的是关联预测的方面，我的数据只有0，1。1代表关联，我想预测关联度，所以是个回归问题，但是也会报CascadeForestRegressor is used for univariate or multi-variate regression, but the target values seem not to be one of them这个错误。我查看了源码，发现会对标签进行判断：type_of_target(y)，结果是'binary'就无法用回归问题。请教一下您这可以解决吗。（正常的随机森林可以做回归预测）

**Comment by xuyxu** [comment]
> 作者您好，我也有这个问题。我做的是关联预测的方面，我的数据只有0，1。1代表关联，我想预测关联度，所以是个回归问题，但是也会报CascadeForestRegressor is used for univariate or multi-variate regression, but the target values seem not to be one of them这个错误。我查看了源码，发现会对标签进行判断：type_of_target(y)，结果是'binary'就无法用回归问题。请教一下您这可以解决吗。（正常的随机森林可以做回归预测）

可以先尝试把label改成float数据类型，看看能不能绕过`type_of_target`的判断。不行的话，直接根据报错的traceback，找到代码源文件，然后把对`type_of_target`的判断注释掉

**Comment by GOD-TEN** [comment]
非常感谢您提出的方案。第一种：把label改成float数据类型，不可行。不过第二种是可行的，非常感谢！
