### ISSUE TITLE
ValueError: Number of features of the model must match the input. Model n_features is 9 and input n_features is 13 

### ISSUE THREAD

**Issue by zhenlingcn** [LAMDA-NJU/Deep-Forest#45]
It seems that the latest version of deep forest has some bugs in terms of "sklearn" backend. I don't know the exact reason, but it seems that there may exist transformation errors in the deep forest package, which makes the data dimensions unmatched in fitting and prediction steps.

> ValueError: Number of features of the model must match the input. Model n_features is 9 and input n_features is 13

**Comment by xuyxu** [comment]
Hi @zhenlingcn, thanks for reporting! Could you provide some codes on reproducing the problem? I will take a look.

**Comment by xuyxu** [comment]
Hi @zhenlingcn, I met the similar problem if the entire model only has one cascade layer. Could you check if this is also the case in your problem?
