### ISSUE TITLE
Is it possible to support the Arm processor? 

### ISSUE THREAD

**Issue by zhenlingcn** [LAMDA-NJU/Deep-Forest#46]
Currently, there are a lot of devices that are running on Arm processors. Thus, supporting the Arm processor is a good idea to allow the deep forest to have much wider application prospects.
![image](https://user-images.githubusercontent.com/18747119/109615489-eb588c80-7b6e-11eb-83d6-828406f7d548.png)

**Comment by xuyxu** [comment]
Hi @zhenlingcn, this should be easy to implement. Could you provide the name of your platform on cibuildwheels https://cibuildwheel.readthedocs.io/en/stable/?

**Comment by zhenlingcn** [comment]
manylinux aarch64

**Comment by xuyxu** [comment]
One question about supporting manylinux aarch64: It looks like [scikit-learn](https://pypi.org/project/scikit-learn/#files) does not officially support manylinux aarch64 as well. Did you build the scikit-learn package from source on your platform?

**Comment by zhenlingcn** [comment]
I'm not so sure whether scikit-learn officially supports aarch64. I installed it on my server using Conda, and the address of the package repository is [link](https://conda.anaconda.org/conda-forge/linux-aarch64/).
