### ISSUE TITLE
安装 DF21的问题

### ISSUE THREAD

**Issue by niliy** [LAMDA-NJU/Deep-Forest#49]
anaconda中安装，确认所需库的版本号正确，运行例子时出现“ numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject”，请问这是为什么

**Comment by xuyxu** [comment]
Hi @niliy, could you show me the version of all packages in `requirements.txt`?

**Comment by niliy** [comment]
> Python 3.7.0
 conda 4.9.2
scikit-learn              0.24.1
numpy                     1.14.5          
numpy-base                1.14.5          
numpydoc                  1.1.0
scipy                     1.1.0
joblib                    1.0.1

**Comment by niliy** [comment]
报错的详细内容如下：
ValueError                                Traceback (most recent call last)
<ipython-input-1-603b3c2d3a60> in <module>
----> 1 from deepforest import CascadeForestClassifier

~\Anaconda3\lib\site-packages\deepforest\__init__.py in <module>
----> 1 from .cascade import CascadeForestClassifier, CascadeForestRegressor
      2 from .forest import RandomForestClassifier, RandomForestRegressor
      3 from .forest import ExtraTreesClassifier, ExtraTreesRegressor
      4 from .tree import DecisionTreeClassifier, DecisionTreeRegressor
      5 from .tree import ExtraTreeClassifier, ExtraTreeRegressor

~\Anaconda3\lib\site-packages\deepforest\cascade.py in <module>
     13 from sklearn.base import is_classifier
     14 
---> 15 from . import _utils
     16 from . import _io
     17 from ._layer import ClassificationCascadeLayer, RegressionCascadeLayer

~\Anaconda3\lib\site-packages\deepforest\_utils.py in <module>
      5 from datetime import datetime
      6 
----> 7 from . import _cutils as _LIB
      8 
      9 

deepforest\_cutils.pyx in init deepforest._cutils()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by xuyxu** [comment]
Thanks, I can reproduce the problem. It looks like updating numpy solves your problem?

``` bash
pip install numpy==1.19.*
```

**Comment by niliy** [comment]
Python  3.6.4 
conda   4.4.10
joblib                    1.0.1
numpy                     1.19.5
scipy                     1.5.4
scikit-learn              0.24.1
这样的配置可执行，感谢您的回复

**Comment by xuyxu** [comment]
Feel free to open another issue if you have any problem :-)
