### ISSUE TITLE
CascadeForestRegressor的参数predictor选择lightgbm无效

### ISSUE THREAD

**Issue by chendingyan** [LAMDA-NJU/Deep-Forest#50]
如果在参数中通过model.set_params(dict)设置use_predcitor =Ture, predictor = 'lightgbm'，实际上在模型中依然predictor为forest

**Comment by xuyxu** [comment]
Thanks @chendingyan, I can reproduce this. This problem roots in the inconsistency on the variable name of predictor: [Link](https://github.com/LAMDA-NJU/Deep-Forest/blob/master/deepforest/cascade.py#L509).

**Comment by xuyxu** [comment]
@all-contributors please add @chendingyan for bug
