### ISSUE TITLE
Please !!!!  I need implement a Model of Multi Inputs Multi Outputs, but I do not know how to do it.

### ISSUE THREAD

**Issue by learningelectric** [LAMDA-NJU/Deep-Forest#57]
你好！
请问我想知道DF21的CascadeForestRegressor或者是CascadeForestClassifier支持输出多个特征吗？（eg:多输入=》model=》多维度的输出）

Hello!
I am very glad to find your greatful and useful work, But I want to know how to implement the Model of Multi Inputs Multi Outputs in DF21 . I really need it in my environment. Can you help me ? 
Please

**Comment by xuyxu** [comment]
Hi @learningelectric, you can check the docstrings of `fit` in our [API  Reference](https://deep-forest.readthedocs.io/en/stable/api_reference.html). Multi-output Regression and Multi-class classification are both supported.

**Comment by learningelectric** [comment]
I really really thank you very much! You are a good man !
