### ISSUE TITLE
Are there any plans to support installation on MacOS?

### ISSUE THREAD

**Issue by jackguagua** [LAMDA-NJU/Deep-Forest#6]
I found that the MacOS version is not yet available in the pypi repository. I wonder if there are plans to provide a mac version, or is there any way to install it manually?

**Comment by xuyxu** [comment]
Hi, thanks for the issue. To use deep forest on Mac OS, here are the instructions:

```
$ git clone https://github.com/LAMDA-NJU/Deep-Forest.git
$ cd Deep-Forest
$ python setup.py install
```

The compilation should run smooth provided that you have installed X-Code, and a valid environment (It is recommended to use the pakcage environment from Anaconda).

Feel free to comment below if you have any problem during the compilation. I have tested it on MacOS Big Sur 11.1, and it looks fine after compilation.

**Comment by jackguagua** [comment]
@xuyxu Great, it does work. Thank you so much for the speedy reply.

I have been looking forward to deep-forest for a long time. My AutoML project [HyperGBM](https://github.com/DataCanvasIO/HyperGBM) based on the gbm model to achieve end-to-end full pipeline automl, currently supports xgboost, lightgbm, catboost algorithms. I am going to add CascadeForestClassifier as its built-in algorithm, and hope to have the opportunity to cooperate further.

**Comment by xuyxu** [comment]
Thanks! We would be happy to see a tool that makes hyper-parameter tunning for deep forest easier ;-) As to cooperation, you may need to contact the leader of our organization.
