### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by niliy** [LAMDA-NJU/Deep-Forest#62]
TypeError: unhashable type: 'slice'
输入的数据是纯数字数据，样本个数与标签匹配，不知道为何会报错。期待并感谢您的回复。

**Comment by niliy** [comment]
以上报错已解决
另外请问下深度深林的输入数据格式是什么样的呢，是原始一维度数据点+标签吗（1*n）？看了下原理介绍，都是这样的，然而参考的代码都是样本特征值+标签(m*n)？

**Comment by xuyxu** [comment]
Glad to hear that @niliy. The input format of training data is `(n_samples, n_features)`, while that of training label is `(n_samples,)`. Besides, `CascadeForestRegressor` also accepts training label of the format `(n_samples, n_outputs)`, i.e., the multi-output regression problem.

FYI: You can check the docstrings of `fit` method in our [API Reference](https://deep-forest.readthedocs.io/en/stable/api_reference.html).

**Comment by xuyxu** [comment]
Closed due to inactivity.
