### ISSUE TITLE
A problem :Size of weights must equal to number of rows

### ISSUE THREAD

**Issue by zshgostop** [LAMDA-NJU/Deep-Forest#63]
When I fit the models, an error raises :
  Check failed: weights_.Size() == num_row_ (385683 vs. 308546) : Size of weights must equal to number of rows.
I have checked the source code of kfoldwrapper, and I find that ：
![image](https://user-images.githubusercontent.com/48615178/111858851-13216000-8977-11eb-9742-30300371100c.png)
Maybe the “sample_weight” should be “sample_weight[train_idx]" ? Otherwise the shape of sample_weight can not math to that of the X

**Comment by xuyxu** [comment]
Hi @zshgostop, I think you are right on this point, will appreciate a PR fixing this very much ;-)

**Comment by xuyxu** [comment]
@all-contributors please add @zshgostop for bug
