### ISSUE TITLE
completely-random tree forests

### ISSUE THREAD

**Issue by LX-Zheng** [LAMDA-NJU/Deep-Forest#68]
I have a question if I want to build a completely-random tree forests should I use ExtraTreesClassifier and how I set max_features?

Thanks for your help

**Comment by xuyxu** [comment]
Hi @long11020, if you are referring to completely random tree, the corresponding estimator should be [RandomTreesEmbedding](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomTreesEmbedding.html), in which each internal node will random select a feature and threshold for splitting. Notice that this is an estimator used in the unsupervised setting.

`ExtraTreesClassifier` is still an estimator for supervised classification. Compared to `RandomForestClassifier`, more randomness is injected into the process of finding the best splitting feature and threshold.

**Comment by long11020** [comment]
Random forest and complete random forest are included in multi-grained-scanning. Which classifier should I use to realize complete random forest?

Thanks for your help

**Comment by xuyxu** [comment]
`RandomForestClassifer` and `ExtraTreesClassifier` [(Reference)](https://github.com/kingfengji/gcForest/blob/master/examples/demo_mnist-gc.json).

**Comment by long11020** [comment]
Thank you so much
