### ISSUE TITLE
如何获取特征变量重要性排序

### ISSUE THREAD

**Issue by wlmszdnb** [LAMDA-NJU/Deep-Forest#75]
DF可以像RF一样获得到特征的重要性排序吗

**Comment by xuyxu** [comment]
Hi @wlmszdnb, the answer is YES.

To get the importance, first train a DF model with `backend` set to `"sklearn"`, then you can use the `get_layer_feature_importances` function to obtian the feature importance per layer.

More info available [here](https://deep-forest.readthedocs.io/en/latest/api_reference.html#get_layer_feature_importances).

**Comment by xuyxu** [comment]
Closed due to inactivity.
