### ISSUE TITLE
Is there a C/C++ interface? How to deploy to a real-world application scenario?

### ISSUE THREAD

**Issue by csuzhhj** [LAMDA-NJU/Deep-Forest#9]

**Comment by xuyxu** [comment]
Hi, thanks for the issue. Developing a C/C++ interface would not be possible with our current workforce :-(

As to the deployment to a real-world application, the model persistence part should work well across different platforms. Let me know if you have any problem when deploying the model to your server or something else.

**Comment by xuyxu** [comment]
Closed due to inactivity.
