### ISSUE TITLE
Could you provide a parameter grid for deep-forest?

### ISSUE THREAD

**Issue by zhenlingcn** [LAMDA-NJU/Deep-Forest#90]
I am glad to see that such a method has achieved promising results on many machine learning tasks. However, in real world scenario, we often tune the hyper-parameter of a specific classifier based on cross-validation scheme. Currently, I am working on constructing a machine learning benchmark, and I believe that a proper set of the parameter grid is vital for fairly comparing the performance between different algorithms. Consequently, could you provide a recommended parameter grid for deep-forest? Or, at least provide a guideline for tuning the hyper-parameter of deep forest?

**Comment by xuyxu** [comment]
Hi @zhenlingcn, does this [page](https://deep-forest.readthedocs.io/en/stable/parameters_tunning.html) help?

**Comment by zhenlingcn** [comment]
Okay, thanks for your response. This page is helpful.

**Comment by simonprovost** [comment]
@hengzhe-zhang Is there a chance we could HPO on `max_features` per Sklearn Random Forest estimators? I looked at the code, the HP not being available, I wonder if there is a way to do that? Custom estimators maybe but how do you pass that through grid-search ?

Cheers
