### ISSUE TITLE
【help】params tuning

### ISSUE THREAD

**Issue by BinchaoPeng** [LAMDA-NJU/Deep-Forest#94]
for my experiment,I set params like this:
```python
parameters = [
    {
        'n_estimators': [2, 5, 8, 10],
        'n_trees': [50, 100, 150, 200, 250, 300],
        'predictors': ['xgboost', 'lightgbm', 'forest'],
        'max_layers': [20, 50, 80, 120, 150],
        'use_predictor': [True]
    },
    {
        'n_estimators': [2, 5, 8, 10, 13],
        'n_trees': [50, 100, 150, 200, 250, 300, 400],
        'max_layers': [20, 50, 80, 120, 150, 200],
    },
]
```

finally, the experiment shows same result with different `predictors` when `use_predictor` is `True`, and different `max_laters` can also get same result.

I would like to konw the situation is correct?

**Comment by xuyxu** [comment]
Please provide more details (e.g., script on the entire training pipeline) and reopen the issue if needed.
