### ISSUE TITLE
Is it possible to add monotone_contraints for deep forest?

### ISSUE THREAD

**Issue by flippercy** [LAMDA-NJU/Deep-Forest#95]
Hi @ThyrixYang, @chendingyan, @xuyxu:

First, thank you for the great library!

I am wondering whether it is possible to add monotone_contraints like what lightgbm/xgboost has to deep forest. This feature is requested for most models used by highly-regulated industries such as financial services, in which the domain knowledge must be respected and followed.

Theoretically, if we specify the monotonicity for a certain feature regarding both estimators and the predictor used by a deep forest model, will the final model be monotonic for this feature globally?

Thank you.

**Comment by flippercy** [comment]
@xuyxu Any updates, please?

**Comment by MrBourriz** [comment]
Any answer by the developpers ? I'm interested
