### ISSUE TITLE
Hello! I want to visualization of feature extraction capability of Deep Forest ! like DNN.

### ISSUE THREAD

**Issue by learningelectric** [LAMDA-NJU/Deep-Forest#96]
Unfortunately, I do not know how to find the augmented feature to visualization of feature extraction capability of Deep Forest !
 If I get the augmented feature from Deep forest, I can using t-SNE tool to make beautiful plot.
The more detail can get in 

https://scikit-learn.org/stable/auto_examples/manifold/plot_t_sne_perplexity.html#sphx-glr-auto-examples-manifold-plot-t-sne-perplexity-py
-----------------------------------------------------------------------------------------------------------------------------
So can you help me ? or give me some advice.
Whatever, I will thank you very much really!!!

**Comment by xuyxu** [comment]
Hi @learningelectric, thanks for this good question!

The augmented features are available [here](https://github.com/LAMDA-NJU/Deep-Forest/blob/master/deepforest/cascade.py#L870), i.e., the variable `X_aug_train_`.

However, getting this variable through hooking currently is not supported. Therefore, my suggestion is

(1) Follow this [guide](https://deep-forest.readthedocs.io/en/stable/installation_guide.html#building-from-source), and install this package using the command `pip install --verbose -e .`
(2) Add the code snippet below in Line 872 of `cascade.py`:
``` python
import joblib
joblib.dump(X_aug_train_, open("X_aug_train_layer_{}.pkl".format(self.n_layers_), "wb"))
```

With these steps done, the model will automatically save augmented features of each cascade layer to your local disk, and you can use `joblib.load` to get augmented features accordingly.

**Comment by learningelectric** [comment]
I sincerely appreciate your help !

**Comment by xuyxu** [comment]
Closed
