### ISSUE TITLE
AttributeError: module 'deepforest' has no attribute 'CascadeForestClassifier'

### ISSUE THREAD

**Issue by yjx4131** [LAMDA-NJU/Deep-Forest#97]
the CascadeForestClassifier function cannot be imported.
I can import deep forest (import deepforest)

**Comment by xuyxu** [comment]
Closed, please provide more details and reopen the issue if needed.

**Comment by Thehonst** [comment]
ImportError: cannot import name 'CascadeForestRegressor' from 'deepforest',why?
