### ISSUE TITLE
Has scanning been excluded from the current deep forest algorithm?

### ISSUE THREAD

**Issue by flippercy** [LAMDA-NJU/Deep-Forest#99]
Hi @ThyrixYang, @xuyxu:

Has the scanning step been excluded from the current deep forest algorithm? It's been described thoroughly in different versions of papers on DF but obviously not implemented in the python package; instead, based on the model architecture, binned raw data is used as the starting point for cascading.

Thank you.

**Comment by malajing** [comment]
I have the same question too.

**Comment by xuyxu** [comment]
Please refer to #26 @malajing

**Comment by malajing** [comment]
> Please refer to #26 @malajing

谢谢~

**Comment by xuyxu** [comment]
Closed due to inactivity.
